name: fixflow_app
description: A Flutter application for client management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
